// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh4aYsOVmTE9Sk5HNCt3j8YjkBh_35GaY',
    appId: '1:676754459168:web:f7051e53a1e9b96fe3ca45',
    messagingSenderId: '676754459168',
    projectId: 'timothyjj-lab-three',
    authDomain: 'timothyjj-lab-three.firebaseapp.com',
    storageBucket: 'timothyjj-lab-three.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0iCtMDVxTHnYY61glkpAkjiRHKd33NFI',
    appId: '1:676754459168:android:f274e3e2c273e587e3ca45',
    messagingSenderId: '676754459168',
    projectId: 'timothyjj-lab-three',
    storageBucket: 'timothyjj-lab-three.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgLhk3OtMU_nkNF-5-VqTT1NXZhzPa7Ho',
    appId: '1:676754459168:ios:72c32903e36fe122e3ca45',
    messagingSenderId: '676754459168',
    projectId: 'timothyjj-lab-three',
    storageBucket: 'timothyjj-lab-three.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgLhk3OtMU_nkNF-5-VqTT1NXZhzPa7Ho',
    appId: '1:676754459168:ios:72c32903e36fe122e3ca45',
    messagingSenderId: '676754459168',
    projectId: 'timothyjj-lab-three',
    storageBucket: 'timothyjj-lab-three.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh4aYsOVmTE9Sk5HNCt3j8YjkBh_35GaY',
    appId: '1:676754459168:web:de680f4a6d68178ae3ca45',
    messagingSenderId: '676754459168',
    projectId: 'timothyjj-lab-three',
    authDomain: 'timothyjj-lab-three.firebaseapp.com',
    storageBucket: 'timothyjj-lab-three.firebasestorage.app',
  );

}